before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w -X main.Version={{.Version}} -X main.GitCommit={{.ShortCommit}} -X github.com/intheclouddan/launchdarkly-code-generator/version.Version={{.Version}}"
    binary: "lcg"
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: lcg

    description: LaunchDarkly Code Generator to build custom flag wrappers

    homepage: "https://launchdarkly.com"

    github:
      owner: launchdarkly-labs
      name: homebrew-tap

    folder: Formula

    url_template: "https://github.com/launchdarkly-labs/lcg/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    install: |
      bin.install "lcg"
    commit_author:
      name: Dan OBrien
      email: dobrien@launchdarkly.com
